/* AgenticEd Certifications — level metadata + question banks.
   Each question: {type:"single"|"multi", q, opts, a (index or array of indices), why}
   Passing score is 70% (14/20) for every level. */
window.AGENTICED_CERTS = {
  order: ["foundational", "associate", "advanced"],
  levels: {
    foundational: {
      id: "foundational",
      tier: "Foundational",
      badge: "🌱",
      name: "AgenticEd Certified: AI & Agent Foundations",
      tagline: "Entry-level credential — core AI agent literacy.",
      summary: "Validates understanding of what an AI agent is, how large language models work, effective prompting, and the basics of responsible AI use.",
      minutes: 30,
      total: 20,
      passScore: 14,
      prerequisite: null,
      questions: [
        {type:"single", q:"Which option best describes an AI agent?",
         opts:["It runs on the largest available model","It pursues a goal through a sequence of actions, observing results and adjusting","It only ever answers a single question","It guarantees a correct answer every time"],
         a:1, why:"An agent is defined by autonomy toward a goal — it acts, observes the outcome, and adapts, rather than producing one fixed response."},
        {type:"single", q:"Put the agent reasoning loop in the correct order.",
         opts:["Act → Observe → Think","Observe → Think → Act","Think → Act → Observe","Act → Think → Observe"],
         a:2, why:"Every agent cycles Think (reason about the goal) → Act (take an action) → Observe (see what happened) — then repeats."},
        {type:"single", q:"At a conceptual level, how does a large language model produce its response?",
         opts:["It searches a verified database for the exact answer","It predicts the most likely next token, based on patterns learned from training data","It copies from a fixed list of approved answers","It consults a human reviewer before responding"],
         a:1, why:"LLMs are next-token predictors trained at massive scale — closer to very sophisticated autocomplete than a lookup system."},
        {type:"single", q:"What is a hallucination?",
         opts:["A hardware malfunction","An AI confidently stating something false because it generated plausible-sounding text rather than retrieving a verified fact","A deliberate lie programmed into the model","Something that only happens in older models"],
         a:1, why:"Hallucination is structural: the model produces text that fits the pattern of a good answer, whether or not it is factually true."},
        {type:"multi", q:"Select all of the following that count as a 'tool' an agent can call to extend what it can do.",
         opts:["A web search API","A calculator function","Pure imagination with no external input","A database query","A weather lookup service"],
         a:[0,1,3,4], why:"Tools are external capabilities — search, computation, data lookups — that give an agent real-time information or reliable actions a bare LLM can't provide on its own."},
        {type:"single", q:"What is the 'context window' of a language model?",
         opts:["Its long-term storage of every past conversation","The amount of text it can consider at once — its short-term working memory","A schedule of when the model is available","A setting that controls font size"],
         a:1, why:"The context window is the model's working memory for the current exchange. Content outside it is effectively invisible to the model."},
        {type:"single", q:"What is a system prompt?",
         opts:["The user's first message","Background instructions that define an agent's role, tone, and boundaries before a user interacts with it","A password required to use the AI","A log of every response ever given"],
         a:1, why:"The system prompt sets the agent's job description — its role, rules, and limits — before any user input arrives."},
        {type:"single", q:"What does 'few-shot' prompting mean?",
         opts:["Asking the same question several times","Including a small number of examples of the desired input/output pattern in the prompt","Giving the model less time to respond","Using very few words in the prompt"],
         a:1, why:"Few-shot prompting shows the model 1–3 examples of the pattern you want, so it can match that pattern immediately. Zero-shot gives no examples."},
        {type:"multi", q:"Select all of the following that are legitimate prompting techniques for improving output quality.",
         opts:["Assigning the AI a role (e.g. 'You are a patient tutor')","Asking for step-by-step reasoning","Typing the whole prompt in ALL CAPS","Specifying the exact output format you want","Including a worked example in the prompt"],
         a:[0,1,3,4], why:"Role assignment, step-by-step instructions, format constraints, and examples are all documented techniques for steering model output. Capitalization has no effect on reasoning quality."},
        {type:"single", q:"What does 'autonomy' mean for an AI agent?",
         opts:["It has no rules or limits at all","It can plan and take steps toward a goal without a human directing every single action","It never needs electricity","It must act completely alone, with no human ever involved"],
         a:1, why:"Autonomy means the agent decides its own next steps toward a goal — it does not mean the absence of human oversight."},
        {type:"single", q:"When an AI agent makes a harmful decision, who is accountable?",
         opts:["No one — it was the AI's own choice","Only the AI system itself","A human — accountability always traces back to the people who built, deployed, or used the agent","Whoever happens to notice the mistake first"],
         a:2, why:"Agents do not bear responsibility — the people who built, deployed, and operated them do."},
        {type:"single", q:"Before acting on a confident AI answer about something important, you should…",
         opts:["Trust it, since it sounded certain","Verify it against an independent source, another tool, or a qualified person","Ask the same AI again if it's sure","Act immediately, since delay reduces accuracy"],
         a:1, why:"Confidence is not the same as accuracy. Independent verification is the habit that separates responsible AI use from blind trust — especially when the stakes are high."},
        {type:"single", q:"What is the key difference between a hallucination and misinformation?",
         opts:["They are the same thing","Hallucination is the mechanism (AI confidently wrong); misinformation is the harm that follows when someone acts on the wrong answer","Misinformation can only come from humans, never AI","Hallucination only happens with numeric answers"],
         a:1, why:"The same false statement is harmless in a low-stakes context and dangerous in a high-stakes one — the distinction matters for deciding when to fact-check before acting."},
        {type:"multi", q:"Select all of the behaviors below that show an app is acting as an agent rather than a simple tool.",
         opts:["It keeps taking actions after its first response to reach a goal","It adapts its plan when conditions change","It performs one fixed calculation and stops","It observes feedback and adjusts its next action"],
         a:[0,1,3], why:"Tools perform one action and stop. Agentic behavior continues: taking further actions, observing outcomes, and adapting — exactly what items 1, 2, and 4 describe."},
        {type:"single", q:"What is a token, in the context of a language model?",
         opts:["A reward given to well-behaved users","The basic unit of text the model processes — roughly a word or part of a word","A type of cryptocurrency","A unique user ID"],
         a:1, why:"Tokens are the chunks of text (often sub-word pieces) that a model reads and generates, one at a time."},
        {type:"single", q:"What is the purpose of 'chain-of-thought' prompting?",
         opts:["To make responses longer for no reason","To ask the model to reason step by step before giving a final answer, which tends to improve accuracy on complex tasks","To hide the model's reasoning from the user","To force the model to skip reasoning entirely"],
         a:1, why:"Chain-of-thought prompting asks the model to show intermediate reasoning steps, which measurably improves performance on multi-step problems."},
        {type:"single", q:"What can a bare LLM (with no tools) NOT reliably do?",
         opts:["Write a short poem","Explain a concept it learned during training","Tell you what happened in the news this morning","Summarize a paragraph you give it"],
         a:2, why:"A bare LLM only knows its training data — it has no access to real-time information unless a tool (like search) is connected to it."},
        {type:"single", q:"What is a prompt?",
         opts:["The AI model's internal weights","The instructions, question, or task given to an AI","The AI's final answer","A bug in the AI's code"],
         a:1, why:"A prompt is the input you give an AI — what you want it to do or answer."},
        {type:"multi", q:"Select all of the responsible-AI habits a foundational-level user should practice.",
         opts:["Fact-check high-stakes answers against an independent source","Assume that a confident tone means the answer is correct","Cite sources when you're uncertain about a claim","Blame the AI model if a decision based on its output turns out wrong"],
         a:[0,2], why:"Responsible use means verifying high-stakes claims and citing sources when unsure. Confidence is not proof of accuracy, and accountability always belongs to people, not the model."},
        {type:"single", q:"A navigation app that watches traffic and reroutes you mid-drive is behaving like…",
         opts:["A simple calculator","A static dictionary lookup","An agent, because it continuously observes feedback and adapts its plan","A search engine returning a list of links"],
         a:2, why:"Continuously observing conditions (traffic) and adjusting the plan (the route) is the Think → Act → Observe loop that defines agentic behavior."}
      ]
    },

    associate: {
      id: "associate",
      tier: "Associate",
      badge: "🛠️",
      name: "AgenticEd Certified: Agent Builder — Associate",
      tagline: "Mid-level credential — building and operating agents.",
      summary: "Validates the ability to design agent system prompts, connect tools and memory, use retrieval-augmented generation, and coordinate multi-agent workflows with human checkpoints.",
      minutes: 35,
      total: 20,
      passScore: 14,
      prerequisite: "foundational",
      questions: [
        {type:"single", q:"In a multi-agent system, what is the role of the orchestrator?",
         opts:["It performs every subtask itself","It breaks the overall goal into subtasks and assigns them to specialist worker agents","It only checks spelling and grammar","It replaces the need for any other agents"],
         a:1, why:"The orchestrator is the manager: it decomposes a goal and directs specialist workers, similar to departments inside a company."},
        {type:"single", q:"What is a 'handoff' in a multi-agent pipeline?",
         opts:["Shutting the whole system down","Passing information, output, or control from one agent to the next","Permanently deleting an agent","A human taking over every task forever"],
         a:1, why:"Handoffs are the points where one agent's output becomes the next agent's input — and where unchecked errors can slip through the pipeline."},
        {type:"single", q:"What is the biggest structural risk in a chain of agents?",
         opts:["It costs slightly more to run","One agent's error can compound as later agents build on it without checking it","The pipeline runs too fast","Agents in a chain cannot communicate at all"],
         a:1, why:"Error compounding is the classic multi-agent failure mode — a flawed research result can become a confident summary, then a published mistake, unless something verifies it in between."},
        {type:"multi", q:"Select all of the actions below that should require a human-approval checkpoint before an agent proceeds.",
         opts:["Sending an email on the user's behalf","Reasoning silently about which source to check next","Spending money or making a purchase","Publishing content publicly","Reading a single public webpage"],
         a:[0,2,3], why:"The rule of thumb is: if an action is irreversible or affects other people — sending, spending, publishing — a human belongs in the loop. Internal reasoning and reading public content are reversible and lower-risk."},
        {type:"single", q:"What are guardrails, in the context of agent design?",
         opts:["Physical barriers placed around server racks","Rules or checks that constrain what an agent is allowed to do, even if its reasoning goes wrong","A brand name for a specific AI model","Backup copies of an agent's code"],
         a:1, why:"Guardrails limit the action space available to an agent — blocked actions, required approvals, content limits — so a confused agent still can't cause serious harm."},
        {type:"single", q:"What does a vector database store, and why is it useful for agents?",
         opts:["Raw video files only","Embeddings — numeric representations of meaning — enabling similarity-based search instead of exact keyword matching","Spreadsheets exclusively","A complete copy of the public internet"],
         a:1, why:"Vector databases index embeddings so a query can retrieve the most semantically similar content, which is the engine behind retrieval-augmented generation (RAG)."},
        {type:"single", q:"The course compares Retrieval-Augmented Generation (RAG) to an open-book test. What does that analogy mean?",
         opts:["The AI is allowed to cheat","Relevant source passages are retrieved and given to the model, so it answers from real material instead of memory alone","The model reads every document that has ever been written before answering","Students are permitted to use AI during open-book exams"],
         a:1, why:"RAG retrieves the right 'pages' and hands them to the model before it answers — the model still reasons, but grounded in specific, citable material."},
        {type:"single", q:"Why do citations matter in a RAG-based tool?",
         opts:["They make responses look longer","They let a user trace an answer back to the exact source passage it came from, so the claim can be verified","They are a legal requirement in every country","They make the system respond faster"],
         a:1, why:"A citation shows exactly where an answer came from. A system that can't point to a source — or invents one — is hallucinating rather than retrieving."},
        {type:"multi", q:"Select all of the elements that belong in a well-designed agent system prompt.",
         opts:["A clear role or persona for the agent","Explicit boundaries describing what the agent must not do","An instruction to never fabricate sources, and to admit uncertainty","An instruction to always sound maximally confident, even when unsure"],
         a:[0,1,2], why:"A good system prompt defines role, boundaries, and an explicit anti-hallucination instruction. Encouraging false confidence directly increases the risk of harmful hallucination."},
        {type:"single", q:"A RAG system is asked a question its source document does not answer. What should a well-designed system do?",
         opts:["Generate a plausible-sounding answer anyway","State clearly that the answer isn't present in the available source","Refuse to answer any future question","Silently search the user's private files without permission"],
         a:1, why:"'Not in the source' is the honest, correct response. A system that invents an answer instead is hallucinating, even if it's built on top of retrieval."},
        {type:"single", q:"Why do experienced builders deliberately try to break their own agent before shipping it?",
         opts:["To waste time before a deadline","Because finding failure modes themselves lets them fix issues before real users encounter them","Because broken agents score better in reviews","It's a superstition with no practical benefit"],
         a:1, why:"Proactively probing for failure modes — the same instinct professional red-teamers use — surfaces problems while they're still cheap to fix."},
        {type:"multi", q:"Select all of the items that belong in an agent's one-page governance policy.",
         opts:["Who the agent is intended for", "What data the agent uses or has access to","Where a human must approve an action before it proceeds","The agent's favorite color"],
         a:[0,1,2], why:"A governance policy documents audience, data use, and human checkpoints — the information someone would need to evaluate whether the agent is safe to deploy."},
        {type:"single", q:"Why do long conversations with an LLM sometimes seem to 'forget' earlier details?",
         opts:["The model is broken","Content outside the context window is invisible to the model, so persistent memory must be stored externally","The model intentionally ignores old messages to save energy","Context windows grow infinitely, so this should never happen"],
         a:1, why:"The context window is finite working memory. Anything that falls outside it is gone unless the system stores it externally and retrieves it again later."},
        {type:"single", q:"What is the practical difference between an agent's context window and an external memory store?",
         opts:["There is no difference","The context window is short-term working memory for the current exchange; an external store (database, file, vector index) persists information across sessions","The context window is for images only","External memory is always faster than the context window"],
         a:1, why:"The context window resets with each new session unless re-supplied; external memory persists facts, preferences, or history beyond any single exchange."},
        {type:"single", q:"An agent returns a confident, detailed answer to a question that touches your organization's policy. What is the most responsible next step before acting on it?",
         opts:["Act immediately since confidence implies correctness","Cross-check the claim against the actual policy document or a qualified person","Ask a different AI the exact same question and assume agreement means correctness","Ignore it, since AI should never be consulted on policy"],
         a:1, why:"Verification against the authoritative source (or a qualified human) is what distinguishes responsible agent use from blind trust in model output."},
        {type:"multi", q:"Select all of the practices that represent a safe handoff between two agents in a pipeline.",
         opts:["Validating the previous agent's output before trusting it downstream","Passing output along unchecked to save processing time","Defining a clear, structured output schema between stages","Using a verifier or critic agent to catch errors before they propagate"],
         a:[0,2,3], why:"Safe handoffs validate output, use structured schemas, and include a verification step — unchecked pass-through is exactly what lets errors compound."},
        {type:"single", q:"What makes a builder's presentation of their agent 'accountable' rather than just a demo?",
         opts:["Using the most technical jargon possible","Explaining what could go wrong, who is responsible if it fails, and what data was used","Avoiding any mention of failures","Focusing only on how visually polished the agent looks"],
         a:1, why:"Accountable presentation closes the loop between building and governing — naming failure modes, responsibility, and data use, not just showing a working demo."},
        {type:"single", q:"What does 'tool use' mean for an LLM-based agent?",
         opts:["The LLM physically operates hardware tools","The LLM can call external functions (search, calculators, APIs, databases) to extend what it can do beyond generating text","The LLM is used as a tool by humans only","The LLM edits its own training data in real time"],
         a:1, why:"Tool use (often via function calling) lets an LLM invoke external capabilities instead of relying solely on what it memorized during training."},
        {type:"single", q:"What is the purpose of embeddings in a retrieval system?",
         opts:["To encrypt user data","To represent text as numeric vectors so that similarity between pieces of content can be measured and searched","To compress video files","To translate text between languages only"],
         a:1, why:"Embeddings turn text into vectors positioned by meaning, enabling similarity search — finding content that means the same thing, not just content with matching keywords."},
        {type:"multi", q:"Select the three questions a builder should be able to answer about their deployed agent.",
         opts:["What could go wrong?","Who is responsible if it fails?","What data did you use?","How much did the server cost to run?"],
         a:[0,1,2], why:"These three accountability questions — failure modes, responsibility, and data — are the core of presenting an agent responsibly, independent of its hosting cost."}
      ]
    },

    advanced: {
      id: "advanced",
      tier: "Advanced / Specialty",
      badge: "🛡️",
      name: "AgenticEd Certified: AI Safety & Governance — Specialty",
      tagline: "Top-tier credential — safety, alignment, and oversight.",
      summary: "Validates the ability to reason about alignment, bias, prompt injection, guardrail design, oversight checkpoints, and deployment risk for agentic systems.",
      minutes: 40,
      total: 20,
      passScore: 14,
      prerequisite: "associate",
      questions: [
        {type:"single", q:"What is the 'alignment problem' in AI safety?",
         opts:["Centering text correctly on a page","Making an AI system pursue the goals its builders actually intend, not just a literal or exploitable version of them","Getting two separate models to produce the same output","Scheduling routine AI system maintenance"],
         a:1, why:"An agent optimizing a goal can find paths its builders never intended. Alignment means the agent's actual behavior matches the intended goal, not just the literal wording of it."},
        {type:"single", q:"What is prompt injection?",
         opts:["Typing a prompt unusually quickly","Malicious instructions hidden in content an agent reads (a webpage, email, or document) that trick it into ignoring its original instructions","A medical procedure unrelated to AI","Submitting a prompt to two different models simultaneously"],
         a:1, why:"If an agent reads external content, attackers can hide instructions inside it. This is a real, observed attack technique against deployed agentic systems — not a theoretical risk."},
        {type:"multi", q:"Select all of the following that are valid mitigations against prompt injection.",
         opts:["Treat all retrieved or external content as untrusted input, not as instructions","Require approval before irreversible actions, even if a tool's output requests them","Automatically trust and act on any instruction found in retrieved content","Limit the agent's permissions so a compromised step can't cause major harm"],
         a:[0,1,3], why:"Defenses include treating external content as data rather than instructions, requiring approval for irreversible actions, and minimizing the agent's permissions — the opposite of blindly trusting retrieved content."},
        {type:"single", q:"What is bias in an AI system?",
         opts:["The AI having a favorite user","Systematic errors in output that reflect unfairness present in the training data or design choices","A hardware defect in the server","A preference for longer answers"],
         a:1, why:"Models learn patterns from the data they're trained on, including existing human unfairness. An agent making hiring or lending decisions can reproduce that unfairness systematically."},
        {type:"single", q:"Why must fairness in an AI system be actively tested rather than assumed?",
         opts:["Because fairness is guaranteed by using a large enough model","Because systematic bias can be invisible until the system's outputs are evaluated against real outcomes across groups","Because testing is required by every programming language","Because fairness only matters for government systems"],
         a:1, why:"Bias can hide inside aggregate accuracy metrics. Testing outcomes across different groups is the only way to surface unfairness that overall accuracy would mask."},
        {type:"multi", q:"Select all of the following that are core Responsible AI principles.",
         opts:["Fairness","Transparency","Accountability","Maximizing popularity","Privacy and safety"],
         a:[0,1,2,4], why:"Fairness, transparency, accountability, and privacy/safety are the standard Responsible AI principles. Popularity is a business metric, not a safety principle."},
        {type:"single", q:"If a deployed AI agent causes real-world harm, who should be held accountable?",
         opts:["No one — software cannot be blamed, and neither can anyone else","The humans who built, deployed, or operated it, depending on their role","Only the electricity provider","The AI system itself, in a legal proceeding"],
         a:1, why:"Accountability always traces to people. 'The AI did it' is never an acceptable final answer — responsibility is distributed across builders, deployers, and operators based on their role."},
        {type:"single", q:"What does 'oversight by design' mean?",
         opts:["Adding human checkpoints only after an incident has already occurred","Designing human-approval checkpoints into the system from the start, before deployment","Removing all human involvement to maximize efficiency","Reviewing the system once a year regardless of changes"],
         a:1, why:"Retrofitting oversight after something goes wrong is how real systems fail. Designing checkpoints in from the start is the safer, more disciplined approach."},
        {type:"single", q:"An agent is about to take an action that cannot be undone and affects someone other than the user. What should happen?",
         opts:["The agent should proceed immediately to stay efficient","The agent should pause for human approval before proceeding","The agent should ask a different AI to approve it instead","The action should be logged only, with no approval required"],
         a:1, why:"Irreversible, other-affecting actions are exactly where a human-approval checkpoint belongs — the litmus test being: if it goes wrong, can it be undone?"},
        {type:"multi", q:"Select all of the following that describe genuine red-teaming activities.",
         opts:["Deliberately trying to make the system fail or misbehave","Assuming only best-case inputs will ever occur","Probing edge cases and adversarial inputs the system wasn't explicitly designed for","Documenting every failure mode that is discovered"],
         a:[0,2,3], why:"Red-teaming means actively trying to break a system with adversarial and edge-case inputs, then documenting what was found — the opposite of assuming only best-case use."},
        {type:"single", q:"What is the main purpose of a human-in-the-loop checkpoint in an agent pipeline?",
         opts:["To slow the system down for no reason","To give a qualified person the chance to catch and correct an error before it causes harm","To make the system appear more trustworthy without changing its behavior","To replace the need for any testing"],
         a:1, why:"A checkpoint exists to let a human intervene before a risky or irreversible step completes — genuine risk reduction, not just appearance."},
        {type:"single", q:"In a classroom debate about deploying AI in a hospital setting, one group proposes specific safeguards — oversight, constraints, and fallback procedures — rather than a simple yes/no stance. What does this illustrate?",
         opts:["That AI should never be used in healthcare under any circumstance","That most real deployment decisions aren't 'should we?' but 'under exactly what safeguards?'","That the group refused to take a position","That speed of deployment matters more than safety"],
         a:1, why:"Real-world deployment decisions are rarely binary. Specifying concrete safeguards is the engineering-ethics skill that turns a debate into an actionable plan."},
        {type:"single", q:"What does it mean to 'constrain the action space' of an agent?",
         opts:["Reducing the number of words the agent is allowed to use","Limiting the set of actions an agent is permitted to take, so that even a reasoning error can't lead to catastrophic outcomes","Making the agent run slower on purpose","Disconnecting the agent from the internet entirely in all cases"],
         a:1, why:"Constraining the action space is a core guardrail technique — restricting what an agent can do, independent of whether its reasoning is correct, limits the blast radius of any mistake."},
        {type:"multi", q:"Select all of the factors that increase the deployment risk of an autonomous agent.",
         opts:["It can take irreversible actions without review","It operates with no logging of its decisions or actions","It operates within a narrow, well-tested scope","It has broad, unchecked permissions across many systems"],
         a:[0,1,3], why:"Irreversible unreviewed actions, lack of logging, and overly broad permissions all raise risk. A narrow, well-tested scope is a risk-reducing property, not a risk factor."},
        {type:"single", q:"Why do organizations need roles like policy analyst, ethics officer, auditor, and red-teamer as AI deployment grows?",
         opts:["These roles are purely ceremonial and have no real function","Someone has to ensure AI systems are used responsibly, and these roles reward judgment, writing, and ethics as much as technical skill","Only programmers are qualified to evaluate AI systems","These roles exist only inside technology companies"],
         a:1, why:"As AI spreads into more decisions, oversight roles are what determine whose interests the system protects — and they reward skills beyond coding."},
        {type:"single", q:"A teacher wants students to practice prompting an AI with example personal data. What is the responsible approach?",
         opts:["Have students use their real names, grades, and personal records for realism","Have students use non-identifying example data, such as a made-up persona or public document","Skip privacy concerns since it's just a classroom exercise","Require every student to create a personal account with real information"],
         a:1, why:"Student records are protected information. Using non-identifying example data avoids exposing real personal records while still letting students practice the skill."},
        {type:"single", q:"In a multi-stage agent pipeline (research → write → fact-check), what is the best safeguard against compounding errors?",
         opts:["Removing the fact-check stage to speed up the pipeline","Adding a verification or review step between stages so errors are caught before they propagate further","Letting every stage trust the previous stage's output completely","Running all three stages simultaneously with no ordering"],
         a:1, why:"A verification step between stages is exactly what prevents one agent's mistake from silently becoming the next agent's confident, uncorrected output."},
        {type:"multi", q:"Select all of the elements of an accountable response when an agent fails publicly.",
         opts:["Clearly naming the specific failure mode that occurred","Hiding the failure and hoping no one notices","Explaining why the failure happened","Describing the fix that was made, or the plan to fix it"],
         a:[0,2,3], why:"Accountable incident response names the failure, explains its cause, and describes a remedy — the opposite of concealment."},
        {type:"single", q:"An agent optimizing for 'maximize user engagement' starts recommending increasingly extreme content because that technically increases engagement. What does this illustrate?",
         opts:["A hardware failure","A misalignment between the literal optimization goal and the outcome the builders actually intended","Proof that engagement metrics are always safe to optimize for","A prompt injection attack"],
         a:1, why:"This is a textbook alignment failure: the system achieved the stated goal through a path the builders did not intend and would not endorse."},
        {type:"single", q:"Before deploying an agent that helps approve or deny loan applications, what is the most responsible first step?",
         opts:["Launch immediately and monitor complaints afterward","Audit the training data and model outputs for bias across protected groups before deployment","Skip testing since financial agents are simpler than medical ones","Let the agent decide its own evaluation criteria"],
         a:1, why:"High-stakes, consequential decisions (like lending) require a proactive bias and fairness audit before deployment — not a reactive one after harm has already occurred."}
      ]
    }
  }
};
